global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sber-teambuilding-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['sber__backend:8080']
        labels:
          application: 'sber-teambuilding-backend'
          service: 'backend'

